# Generated by Django 4.2.7 on 2023-11-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question'),
        ('chatbotAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatable',
            name='question_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
