# Generated by Django 4.2.7 on 2023-11-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0002_alter_qatable_question_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qatable',
            name='question_summary',
        ),
    ]
