# Generated by Django 4.2.7 on 2023-11-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0005_qatable_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qatable',
            old_name='a',
            new_name='answer_content',
        ),
        migrations.RenameField(
            model_name='qatable',
            old_name='q',
            new_name='question_content',
        ),
        migrations.RemoveField(
            model_name='qatable',
            name='label',
        ),
    ]
