# Generated by Django 4.2.7 on 2023-11-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0007_qatable_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qatable',
            old_name='answer_content',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='qatable',
            old_name='question_content',
            new_name='q',
        ),
    ]
