# Generated by Django 4.1 on 2023-11-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0008_rename_answer_content_qatable_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qatable',
            name='created_at',
        ),
    ]
