# Generated by Django 4.1 on 2023-12-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_password'),
        ('chatbotAdmin', '0009_remove_qatable_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatable',
            name='pw',
            field=models.ForeignKey(default='default_password', on_delete=django.db.models.deletion.CASCADE, related_name='qatable_pw_set', to='main.question', to_field='password'),
            preserve_default=False,
        ),
    ]
