# Generated by Django 4.1 on 2023-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0011_remove_qatable_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatable',
            name='pw_id',
            field=models.CharField(default='some_default_value', max_length=255),
        ),
    ]
