# Generated by Django 4.1 on 2023-12-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotAdmin', '0012_qatable_pw_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qatable',
            name='pw_id',
        ),
    ]
