# Generated by Django 4.2.7 on 2023-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[('N', 'Not Answered'), ('Y', 'Answered')], default='N', max_length=1),
        ),
    ]
