# Generated by Django 4.2.7 on 2023-11-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_answer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
