# Generated by Django 4.1 on 2023-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='password',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
