# Generated by Django 4.1 on 2023-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
